config/routes.rb
Backstage::Application.routes.draw do

  devise_for :admin_users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  resources :tablets
  
  resources :menus do
    resources :menu_items
  end
  
  resources :menu_items
  root :to => 'dashboard#home'
  match '/assign' => 'tablets#assign'
  match '/assign_tablets' => 'tablets#assign_tablets'
  match '/show_assignment' => 'tablets#show_assignment'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :owner
  has_many :menu_items
  has_many :categories

  accepts_nested_attributes_for :menu_items, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :categories, :reject_if => :all_blank, :allow_destroy => true
  attr_accessible :menu_type, :name, :menu_items_attributes, :categories_attributes
  validates_uniqueness_of :name
  validates_presence_of :menu_type, :name
  
  attr_writer :current_step
  
  def current_step
    @current_step || steps.first
  end
  
  def steps
    %w[category_step menu_items_step]
  end
  
  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end
  
  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end
  
  def first_step?
    self.current_step == steps.first
  end
    
  def last_step?
    self.current_step == steps.last
  end
  
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_filter :authenticate_admin_user!
  # GET /menus
  # GET /menus.json

  def index
    @current_admin_user = current_admin_user
    @menus = Menu.all
    @title = "Menus"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @current_admin_user = current_admin_user    
    @menu = Menu.find(params[:id])
    @menu_items = @menu.menu_items
    @title = @menu.name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => {:menu => @menu, :menu_items => @menu_items} }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @current_admin_user = current_admin_user
    session[:menu_params] ||= {}
    @title = "New Menu"
    @menu = Menu.new(session[:menu_params])
    @categories = @menu.categories
    @menu.current_step = session[:menu_step]
  end

  # GET /menus/1/edit
  def edit
    @current_admin_user = current_admin_user
    session[:menu_update_params] ||= {}
    @menu = Menu.find(params[:id])
    @title = @menu.name
    @categories = @menu.categories
    session[:menu_id] = @menu.id
    session[:menu_step] = @menu.current_step
  end

  # POST /menus
  # POST /menus.json
  def create
    @current_admin_user = current_admin_user
    session[:menu_params].deep_merge!(params[:menu]) if params[:menu]
    @menu = Menu.new(session[:menu_params])
    @categories = @menu.categories
    @menu.current_step = session[:menu_step]
    @selected_type = @menu.menu_type
    puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #{@selected_type}"
    if params[:back_button]
      @menu.previous_step
    elsif @menu.last_step?
      @menu.save
    else
      @menu.next_step
    end
    session[:menu_step] = @menu.current_step
    if @menu.new_record?
      render "new"
    else
      session[:menu_steps]=session[:menu_params] = nil
      redirect_to @menu, notice: "Menu was successfully created."
    end
  end

 
  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @current_admin_user = current_admin_user
    @menu = Menu.find(params[:id])
    @title = @menu.name
    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def destroy_menu_item
    @current_admin_user = current_admin_user
    @menu = Menu.find(params[:menu_id])
    @menu_item = @menu.menu_items.find(params[:id])
    @menu_item.destroy
    respond_to do |format|
      format.html {redirect_to @menu}
      format.json {head :no_content}
    end
  end
  
  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @current_admin_user = current_admin_user
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
      format.js
    end
  end
  
  def daily_special
    
  end
  
  private
  def get_categories(menu)
    categories = []
    menu.categories.each {|category| categories << category.name}
  end
    
end

app/views/menus/_category_fields.html.slim
.nested-fields
  table
    tr
      td
        = f.input :name, :wrapper => :inline, :label => false, :hint => 'Category' do
          = f.input_field :name, :hint => 'Category'
      td
        = link_to_remove_association "remove item", f, :class => "btn btn-mini btn-danger"

app/views/menus/_category_step.html.slim
#category
= f.simple_fields_for :categories do |category|
  = render 'category_fields', :f => category
.links
  = link_to_add_association 'Add Category', f, :categories,
		:render_options => {:wrapper => 'inline'}, :class => 'btn btn-primary'

app/views/menus/_form.html.slim
= simple_form_for @menu, :html => {:multipart => true}, :wrapper => 'inline' do |f|
  = f.input :name, :hint => 'Just a name for your menu'
  = f.input :menu_type, :hint => 'Type of menu'
  = render "#{@menu.current_step}", :f => f
		
  br
  .actions
  = f.button :submit, "Continue", :disable_with => 'Please wait ...'
  = f.button :submit, "Back", :name => 'back_button', :disable_with => 'Please wait ...' unless @menu.first_step?

app/views/menus/_menu_item_fields.html.slim
.nested-fields
  table
    tr
      td
        = f.input :name, :wrapper => :inline, :label => false, :hint => 'Item Name' do
          = f.input_field :name, :hint => 'Item Name'
      td
        = f.input :description, :wrapper => :inline, :label => false, :hint => 'Item Description' do
          = f.input_field :description, :rows => "5", :hint => 'Item Description'
      td
        = f.input :price, :wrapper => :inline, :label => false, :hint => 'Item Price' do
          = f.input_field :price, :hint => 'Item Price'
      td
        = f.input :category, :wrapper => :inline, :label => false, :hint => 'Category' do
          = f.select(:category, @categories.collect {|category| [ category.name] })
	  td 
	   = f.input :item_asset, :wrapper => :inline, :label => false, :hint => 'Image' do
	     = f.file_field :item_asset
	   
      td
        = link_to_remove_association "remove item", f, :class => "btn btn-mini btn-danger"

app/views/menus/_menu_items_step.html.slim
= f.simple_fields_for :menu_items do |menu_item|
  = render 'menu_item_fields', :f => menu_item
.links
  = link_to_add_association 'Add Item', f, :menu_items, 
 :render_options => { :wrapper => 'inline' }, :class => 'btn btn-primary'

app/views/menus/daily_special.slim
h1 New Menu

== render 'form'

= link_to 'Back', menus_path

app/views/menus/edit.html.slim
= simple_form_for @menu, :html => {:multipart => true}, :wrapper => 'inline' do |f|
  = f.input :name, :hint => 'Just a name for your menu'
  = f.input :menu_type, :hint => 'Type of menu'
  = render "#{@menu.current_step}", :f => f

  br
  .actions
  = f.button :submit, "Update", :disable_with => 'Please wait ...'
 
= link_to 'Back', menus_path

app/views/menus/index.html.slim
h1 Listing Menus

div class="well"
 table class="table"
  thead
    tr
      th Menu
      th Actions
  tbody
    - @menus.each do |menu|
      tr
        td= link_to menu.name, menu_path(menu)
        td
		  = link_to 'Edit', edit_menu_path(menu), :class => 'icon-pencil'
		  = " "
		  = link_to 'Delete', menu, :confirm => 'Are you sure?', :method => :delete, :class => 'icon-remove'

p
 = link_to 'New Menu', new_menu_path, :class => 'btn btn-primary'
p

app/views/menus/new.html.slim
h1 New Menu

== render 'form'

= link_to 'Back', menus_path

app/views/menus/show.html.slim
h3 Menu Items

table class="table table-striped"
  tr
   th 
   th Item Name
   th Item Description
   th Item Price
   th Category	
   th Actions
   th
  -@menu_items.each do |item|
    tr
	  td= image_tag item.item_asset.url(:small)
      td= link_to item.name, menu_menu_item_path(item.menu, item)
      td= item.description
      td= item.price
	  td= item.category
	  td= link_to 'Edit', edit_menu_menu_item_path(item), :class => 'icon-pencil' 
	  td= link_to 'Delete', menu_menu_item_path(item.id), :confirm => 'Are you sure?', :method => :delete, :class => 'icon-remove'
p
 = link_to 'Edit', edit_menu_path(@menu)
 = ' | '
 = link_to 'Back', menus_path
 = ' | '
 = link_to 'Add New Item', new_menu_menu_item_path(@menu)