config/routes.rb
Backstage::Application.routes.draw do

  devise_for :admin_users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  resources :tablets
  
  resources :menus do
    resources :menu_items
  end
  
  resources :menu_items
  root :to => 'dashboard#home'
  match '/assign' => 'tablets#assign'
  match '/assign_tablets' => 'tablets#assign_tablets'
  match '/show_assignment' => 'tablets#show_assignment'

end

app/models/tablet.rb
class Tablet < ActiveRecord::Base
  belongs_to :owner
  
  attr_accessible :ip_address, :is_server, :owner_id, :restaurant_id, :serial_no
  
  validates :serial_no, :uniqueness => true
end

app/controllers/tablets_controller.rb
class TabletsController < ApplicationController
  before_filter :authenticate_admin_user!
  # GET /tablets
  # GET /tablets.json
  def index
    current_admin_user
    @tablets = Tablet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tablets }
    end
  end

  # GET /tablets/1
  # GET /tablets/1.json
  def show
    current_admin_user
    @tablet = Tablet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tablet }
    end
  end

  def assign
    current_admin_user
    # restaurants = Restaurant.all
    # @restaurants = []
    # restaurants.each {|restaurant| @restaurants << restaurant.name }
    @restaurants = Restaurant.all
  end

  def assign_tablets
    puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #{params}"
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! RESTAURANT ID #{params["assign_tablets"]["restaurant_id"]}"
    restaurant_id = params["assign_tablets"]["restaurant_id"]
    restaurant = Restaurant.find(restaurant_id.to_i)
    tablets = params["assign_tablets"]["number_of_tablets"]
    @tablets = Tablet.where(:restaurant_id => nil).limit(tablets)
    updated = false
    errors = {}
    @tablets.each do |tablet|
      if tablet.update_attributes(:owner_id => restaurant.owner_id, :restaurant_id => restaurant.id)
        updated = true
      else
        updated = false
        errors = tablet.errors
      end
    end
    respond_to do |format|
      if updated
        format.html { redirect_to root_path, notice: 'Tablet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "assign" }
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  
  def show_assignment
    
  end
  
  # GET /tablets/new
  # GET /tablets/new.json
  def new
    current_admin_user
    @tablet = Tablet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tablet }
    end
  end

  # GET /tablets/1/edit
  def edit
    current_admin_user
    @tablet = Tablet.find(params[:id])
  end

  # POST /tablets
  # POST /tablets.json
  def create
    current_admin_user
    @tablet = Tablet.new(params[:tablet])

    respond_to do |format|
      if @tablet.save
        format.html { redirect_to @tablet, notice: 'Tablet was successfully created.' }
        format.json { render json: @tablet, status: :created, location: @tablet }
      else
        format.html { render action: "new" }
        format.json { render json: @tablet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tablets/1
  # PUT /tablets/1.json
  def update
    current_admin_user
    @tablet = Tablet.find(params[:id])

    respond_to do |format|
      if @tablet.update_attributes(params[:tablet])
        format.html { redirect_to @tablet, notice: 'Tablet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tablet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tablets/1
  # DELETE /tablets/1.json
  def destroy
    current_admin_user
    @tablet = Tablet.find(params[:id])
    @tablet.destroy

    respond_to do |format|
      format.html { redirect_to tablets_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/views/tablets/_form.html.erb
<%= simple_form_for(@tablet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :serial_no %>
    <%= f.input :ip_address%>
	<%= f.input :is_server%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tablets/assign.html.erb
<%= simple_form_for :assign_tablets, { url: assign_tablets_path } do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
	  <%=f.label "Restaurant"%>
  <%=f.select :restaurant_id, @restaurants.collect {|restaurant| [restaurant.name, restaurant.id]}, {include_blank: 'None'}  %>	
  
    <%= f.input :number_of_tablets %>
	
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Assign", :class => 'btn btn-primary' %>
  </div>
<% end %>
<p>
  
</p>



<%= link_to 'Back', tablets_path %>

app/views/tablets/edit.html.erb
<h1>Editing tablet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tablet %> |
<%= link_to 'Back', tablets_path %>

app/views/tablets/index.html.erb
<h1>Listing tablets</h1>

<table>
  <tr>
    <th>Serial no</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tablets.each do |tablet| %>
  <tr>
    <td><%= tablet.serial_no %></td>
    <td><%= link_to 'Show', tablet %></td>
    <td><%= link_to 'Edit', edit_tablet_path(tablet) %></td>
    <td><%= link_to 'Destroy', tablet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to "Assign Tablets", assign_path, :class => 'btn btn-primary'%>
<%= link_to 'New Tablet', new_tablet_path, :class => 'btn btn-primary' %>

app/views/tablets/new.html.erb
<h1>New tablet</h1>

<%= render 'form' %>

<%= link_to 'Back', tablets_path %>

app/views/tablets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Restaurant:</b>
  <%= @tablet.restaurant_id %>
</p>

<p>
  <b>Ip address:</b>
  <%= @tablet.ip_address %>
</p>

<p>
  <b>Is server:</b>
  <%= @tablet.is_server %>
</p>

<p>
  <b>Owner:</b>
  <%= @tablet.owner_id %>
</p>

<p>
  <b>Serial no:</b>
  <%= @tablet.serial_no %>
</p>


<%= link_to 'Edit', edit_tablet_path(@tablet) %> |
<%= link_to 'Back', tablets_path %>