config/routes.rb
Backstage::Application.routes.draw do

  devise_for :admin_users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  resources :tablets
  
  resources :menus do
    resources :menu_items
  end
  
  resources :menu_items
  root :to => 'dashboard#home'
  match '/assign' => 'tablets#assign'
  match '/assign_tablets' => 'tablets#assign_tablets'
  match '/show_assignment' => 'tablets#show_assignment'

end

app/views/layouts/_messages.html.erb
  <%if flash[:alert] || flash[:notice] || flash[:error]%>
    <div class ="<%=notice_type(@notice || "")%>" id ="flash">
      <%=flash[:alert] || flash[:error] || flash[:notice]%></div>
  <%end%>

app/views/layouts/_notice.html.slim
div class="alert alert-#{id}"
 a class="close" data-dismiss="alert" href="" X
 =notice 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grubshire Backstage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
	    <div class="navbar-inner">
	      <div class="container">
	        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </a>
			<%=link_to "GrubShire", root_path, :class => "brand"%>
	        <div class="nav-collapse">
	        <%if admin_user_signed_in?%>	
			  <ul class="nav">
	            <li><%=link_to "Menus", menus_path%></li>
				<li><%= link_to "Tablets", tablets_path%>
	          </ul>
			  <form class="navbar-search pull-right" action="">
			     <input type="text" class="search-query span2" placeholder="Search">
			   </form>
			  <ul class="nav pull-right">
			    <li class="dropdown">
			      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=@current_admin_user.email%> <b 	class="caret"></b></a>
			      <ul class="dropdown-menu">
			        <li><%=link_to "Sign Out", destroy_admin_user_session_path, :method => 'delete'%></li>
			        <li><%=link_to "My Account"%></li>
			      </ul>
			    </li>
			  </ul>
			  <%end%>
	        </div>
	      </div>
	    </div>
	  </div>

	  <div class="container">
	    <div class="row">
			<%if notice%>
				<%=render "layouts/notice", :notice => (notice||alert), :id =>"notice"%>
			<%elsif alert%>
				<%=render "layouts/notice", :notice => (notice||alert), :id =>"error"%>
			<%end%>
	      <div class="span10"><%= yield %></div>
	     
	    </div>
	  </div>
  <%= javascript_include_tag :application %>
</body>
</html>